# Generated by Django 5.1 on 2024-08-26 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_image_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='is_private',
            new_name='is_primary',
        ),
    ]
